[package]
name = "ipfs-gateway-finder"
version = "0.2.0"
authors = ["Leo Balduf <leobalduf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-resolver-common = {path = "../common"}
wantlist-client-lib = {path = "../wantlist-client-lib"}
failure = "0.1.7"
log = "0.4.8"
dotenv = "0.15.0"
flexi_logger = "0.15.2"
reqwest = { version = "0.10.4", features = ["blocking","json"] }
multibase = "0.8.0"
chrono = "0.4.11"
serde = "1.0.110"
serde_json = "1.0.51"
tokio = { version = "0.2.21", features = ["rt-threaded","macros","sync"] }
rand = "0.7.3"
parity-multiaddr = "0.9.0"
ipfs-api = "0.7.2"
cid = "0.5.1"
http = "0.2.1"
csv = "1.1.6"
clap = "2.33.3"