# This is a config file for the unify-bitswap-traces tool.
monitors:
  - monitor_name: "de1"
    input_globs:
      - "../../../archive/wantlists-de1/wantlist.json.2021-04-30*.gz"
      - "../../../archive/wantlists-de1/wantlist.json.2021-05-01*.gz"
      - "../../../archive/wantlists-de1/wantlist.json.2021-05-02*.gz"
      - "../../../archive/wantlists-de1/wantlist.json.2021-05-03*.gz"
      - "../../../archive/wantlists-de1/wantlist.json.2021-05-04*.gz"
      - "../../../archive/wantlists-de1/wantlist.json.2021-05-05*.gz"
      - "../../../archive/wantlists-de1/wantlist.json.2021-05-06*.gz"
  - monitor_name: "us1"
    input_globs:
      - "../../../archive/wantlists-us1/wantlist.json.2021-04-30*.gz"
      - "../../../archive/wantlists-us1/wantlist.json.2021-05-01*.gz"
      - "../../../archive/wantlists-us1/wantlist.json.2021-05-02*.gz"
      - "../../../archive/wantlists-us1/wantlist.json.2021-05-03*.gz"
      - "../../../archive/wantlists-us1/wantlist.json.2021-05-04*.gz"
      - "../../../archive/wantlists-us1/wantlist.json.2021-05-05*.gz"
      - "../../../archive/wantlists-us1/wantlist.json.2021-05-06*.gz"
message_sorting_window_size: 1000
wantlist_output_file_pattern: "csv/wl-$id$.csv.gz"
ledger_count_output_file: "csv/ledgers.csv.gz"
matching_config:
  inter_monitor_matching_window_milliseconds: 5000
  global_duplicate_window_seconds: 31
  match_newest_first: false
  allow_multiple_match: false
  match_exact_entry_type: false
simulation_config:
  allow_empty_full_wantlist: false
  allow_empty_connection_event: false
  insert_full_wantlist_synth_cancels: true
  insert_disconnect_synth_cancels: true
  reconnect_duplicate_duration_secs: 5
  sliding_window_lengths: [1,9,11,29,31,601,3601,604801]